"""initial migration

Revision ID: d349f1500ee5
Revises: 
Create Date: 2026-04-07 16:32:20.408466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd349f1500ee5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_summary')
    op.drop_table('fuel_transaction')
    with op.batch_alter_table('power_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uix_power_schedule_station_date_time'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('power_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uix_power_schedule_station_date_time'), ['id_tram', 'ngay_mat_dien', 'thoi_gian_cup_dien'], unique=True)

    op.create_table('fuel_transaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('ngay', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('id_tram', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('loai_nhien_lieu', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('so_luong', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('don_gia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('thanh_tien', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nha_cung_cap', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('nguoi_thuc_hien', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ghi_chu', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('ngay_cap_nhat', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ngay_su_dung', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('noi_dung', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('du_an', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('so_tien', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nguoi_tam_ung', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fuel_transaction_pkey'))
    )
    op.create_table('station_summary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_tram', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('thang', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('tong_gio_chay', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tong_lich_cup', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dau_ton', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tong_do_vao', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tong_tieu_hao', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('chi_phi_dau', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('doanh_thu', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ngay_cap_nhat', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('station_summary_pkey'))
    )
    # ### end Alembic commands ###
